// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY94SxHVBjRadKkrpBTGBCKAj0JkR6zlo',
    appId: '1:771277167632:web:ab961377b306116ca33e95',
    messagingSenderId: '771277167632',
    projectId: 'ecmobile-2e7c7',
    authDomain: 'ecmobile-2e7c7.firebaseapp.com',
    storageBucket: 'ecmobile-2e7c7.firebasestorage.app',
    measurementId: 'G-7DP6ZL8G8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6ASlb3xQZcUUUt-HkXqXHovXKqcoqdA',
    appId: '1:771277167632:android:8bf50544a56e902ea33e95',
    messagingSenderId: '771277167632',
    projectId: 'ecmobile-2e7c7',
    storageBucket: 'ecmobile-2e7c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5_08UD7KaEOXcWzetMXcrwGDFV-udZMc',
    appId: '1:771277167632:ios:1aa994bdbd7a8b13a33e95',
    messagingSenderId: '771277167632',
    projectId: 'ecmobile-2e7c7',
    storageBucket: 'ecmobile-2e7c7.firebasestorage.app',
    iosBundleId: 'com.example.ecmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5_08UD7KaEOXcWzetMXcrwGDFV-udZMc',
    appId: '1:771277167632:ios:1aa994bdbd7a8b13a33e95',
    messagingSenderId: '771277167632',
    projectId: 'ecmobile-2e7c7',
    storageBucket: 'ecmobile-2e7c7.firebasestorage.app',
    iosBundleId: 'com.example.ecmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY94SxHVBjRadKkrpBTGBCKAj0JkR6zlo',
    appId: '1:771277167632:web:7922f76f3062d641a33e95',
    messagingSenderId: '771277167632',
    projectId: 'ecmobile-2e7c7',
    authDomain: 'ecmobile-2e7c7.firebaseapp.com',
    storageBucket: 'ecmobile-2e7c7.firebasestorage.app',
    measurementId: 'G-F9TEZ2EEXN',
  );
}
